### ISSUE TITLE
Generate a new release

### ISSUE THREAD

**Issue by sergiughf** [dnephin/pre-commit-golang#26]
Hey there,

Could we kindly have a new release that has this https://github.com/dnephin/pre-commit-golang/pull/24 within it? :)

**Comment by dnephin** [comment]
I just merged #25 which has a fix for that change, does it still work for you?

If it still looks good, I can tag a release

**Comment by sergiughf** [comment]
Yep, just tested https://github.com/dnephin/pre-commit-golang/commit/88296473687faba85dcbd8e151fa15e45a66d0b8 and works like a charm! Would be great if we can do that! Thanks :yellow_heart:

**Comment by dnephin** [comment]
https://github.com/dnephin/pre-commit-golang/tree/v0.3.3

**Comment by sergiughf** [comment]
Thank you so much! 

![image](https://user-images.githubusercontent.com/28300158/54077632-6017c980-42bb-11e9-90e9-8c2110bbd397.png)
