### ISSUE TITLE
How about `go mod tidy` ?

### ISSUE THREAD

**Issue by ash-r1** [dnephin/pre-commit-golang#45]
In my experience, sometimes we add a wrong library to the project.

In this case, we do `go mod tidy` if we use `go mod` feature.

I'm happy if it's supported by this project.

**Comment by Jerome1337** [comment]
@ash-r1 `go mod tidy` has been added with #43

**Comment by ash-r1** [comment]
@Jerome1337 Awesome! 👍👍👍
