### ISSUE TITLE
Cannot update because the tip of HEAD is missing these hooks: go-mod-tidy

### ISSUE THREAD

**Issue by bwitt** [dnephin/pre-commit-golang#57]
I have `go-mod-tidy` configured in my `.pre-commit-config.yaml` and if I try to run `pre-commit autoupdate` I get this error

```
...
Updating git://github.com/dnephin/pre-commit-golang ... Cannot update because the tip of HEAD is missing these hooks:
go-mod-tidy
...
```

I think this is because there hasn't been a release since https://github.com/dnephin/pre-commit-golang/commit/3c835496ef7101a0d1e1e44afa02f361683382b1 was merged.

**Comment by AuthorProxy** [comment]
still not working
```
git add .pre-commit-config.yaml && pre-commit autoupdate && pre-commit
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating git://github.com/dnephin/pre-commit-golang ... Cannot update because the update target is missing these hooks:
go-mod-tidy
```

**Comment by AuthorProxy** [comment]
pre-commit
```[ERROR] `go-mod-tidy` is not present in repository git://github.com/dnephin/pre-commit-golang.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.```

**Comment by dnephin** [comment]
I tagged https://github.com/dnephin/pre-commit-golang/releases/tag/v0.4.0

**Comment by bwitt** [comment]
it's working for me now thanks!
