### ISSUE TITLE
`golang/go-lint` is deprecated & unmaintained

### ISSUE THREAD

**Issue by Jarmos-san** [dnephin/pre-commit-golang#89]
The [`golang/go-lint`](https://github.com/golang/go-lint) project has been deprecated in favour of using `go vet` & other tools like [staticcheck](https://staticcheck.io). Doesn't it make more sense to either let the user of the hook know about it in the README (or perhaps remove it all together?

Better alternatives include:

- [`go-critic`](https://github.com/go-critic/go-critic)
- [`golangci-lint`](https://github.com/golangci/golangci-lint) which more feature-rich

**Comment by dnephin** [comment]
`golangci-lint` is already supported. I think it would be good to mention in the README that the `go-lint` hook is deprecated in favor of `golangci-lint`. A pull request for this would be welcome.  Thank you!
